# Multiple keyservers for GPG key fetching reliability. Fast timeout so a
# dead keyserver doesn't block key operations for 30s.
# Mirrors omarchy default/gpg/dirmngr.conf.
keyserver hkps://keyserver.ubuntu.com
keyserver hkps://pgp.surfnet.nl
keyserver hkps://keys.mailvelope.com
keyserver hkps://keyring.debian.org
keyserver hkps://pgp.mit.edu

connect-quick-timeout 4
